apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-abb-prod
  labels:
    app: abb-app
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abb-app
      environment: prod
  template:
    metadata:
      labels:
        app: abb-app
        environment: prod
    spec:
      containers:
      - name: abb-app
        image: 261884385716.dkr.ecr.us-west-1.amazonaws.com/abb-docker-repo:$BUILD_NUMBER'
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "prod"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
